services:
  penpot-frontend:
    image: penpotapp/frontend:latest
    container_name: ${PENPOT_FRONTEND_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - '${PENPOT_FRONTEND_HTTP_PORT}:8080'
      - '${PENPOT_FRONTEND_WS_PORT}:9001'
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    environment:
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies

  penpot-backend:
    image: penpotapp/backend:latest
    container_name: ${PENPOT_BACKEND_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    environment:
      PENPOT_PUBLIC_URI: http://${DOMAIN_NAME}
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
      PENPOT_DATABASE_URI: postgresql://penpot-postgres/penpot
      PENPOT_DATABASE_USERNAME: penpot
      PENPOT_DATABASE_PASSWORD: penpot
      PENPOT_REDIS_URI: redis://penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: true
      PENPOT_SMTP_DEFAULT_FROM: no-reply@example.com
      PENPOT_SMTP_DEFAULT_REPLY_TO: no-reply@example.com
      PENPOT_SMTP_HOST: penpot-mailcatch
      PENPOT_SMTP_PORT: 1025
      PENPOT_SMTP_USERNAME: ${PENPOT_SMTP_USERNAME}
      PENPOT_SMTP_PASSWORD: ${PENPOT_SMTP_PASSWORD}
      PENPOT_SMTP_TLS: false
      PENPOT_SMTP_SSL: false

  penpot-exporter:
    image: penpotapp/exporter:latest
    container_name: ${PENPOT_EXPORTER_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      PENPOT_PUBLIC_URI: http://penpot-frontend
      PENPOT_REDIS_URI: redis://penpot-redis/0

  penpot-postgres:
    image: postgres:latest
    container_name: ${PENPOT_POSTGRES_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    stop_signal: SIGINT
    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_DB: penpot
      POSTGRES_USER: penpot
      POSTGRES_PASSWORD: penpot

  penpot-redis:
    image: redis:latest
    container_name: ${PENPOT_REDIS_CONTAINER_NAME}
    restart: ${RESTART_POLICY}

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    container_name: ${PENPOT_MAILCATCHER_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    expose:
      - '1025'
    ports:
      - '${MAILCATCHER_HTTP_PORT}:1080'

volumes:
  penpot_postgres_data:
  penpot_assets:
