services:
  neo4j:
    image: neo4j:latest
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
    ports:
      - '${PORT_HTTP}:7474'
      - '${PORT_BOLT}:7687'
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
