services:
  netdata:
    image: netdata/netdata:${NETDATA_TAG}
    container_name: ${NETDATA_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - "${NETDATA_PORT}:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata-config:/etc/netdata
      - netdata-cache:/var/cache/netdata
      - netdata-lib:/var/lib/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdata-config:
  netdata-cache:
  netdata-lib:
