services:
  influxdb:
    image: influxdb:latest
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_DB: ${INFLUXDB_DB}
    ports:
      - '${PORT}:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
