services:
  redis:
    image: redis:latest
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - '${PORT}:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
