services:
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: ${GRAFANA_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

volumes:
  grafana-data:
