services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '${PORT}:80'
