services:
  ollama:
    image: ollama/ollama:${OLLAMA_TAG}
    container_name: ${OLLAMA_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    tty: true
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "${OLLAMA_PORT}:11434"

volumes:
  ollama-data:
