services:
  mysql:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '${PORT}:3306'

volumes:
  mysql-data:
