services:
  wordpress:
    image: wordpress:${WP_TAG}
    container_name: ${WP_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - '${WP_PORT}:80'

  db:
    image: mysql:${DB_TAG}
    container_name: ${DB_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'

volumes:
  wordpress_data:
  db_data:
