services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_TAG}
    container_name: ${PORTAINER_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
